<?xml version="1.0"?>
<package format="3">
  <name>crazyflie_controller</name>
  <version>2.0.0</version>
  <description>NMPC controller for the Crazyflie 2.1</description>

  <maintainer email="barros@diag.uniroma1.it">Barbara Barros Carlos</maintainer>
  <maintainer email="tommaso.sartor@imtek.uni-freiburg.de">Tommaso Sartor</maintainer>

  <license>MIT</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies needed at build time -->
  <build_depend>rclcpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>tf2_ros</build_depend> 

  <!-- Dependencies needed at run time -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>tf2_ros</exec_depend> 

  <export>
    <!-- Mark as an ament package -->
    <build_type>ament_cmake</build_type>
  </export>
</package>
