/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crazyflie_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* crazyflie_expl_ode_fun:(i0[13],i1[4])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][7] : 0;
  a1=2.;
  a2=arg[0] ? arg[0][3] : 0;
  a3=casadi_sq(a2);
  a3=(a1*a3);
  a4=arg[0] ? arg[0][4] : 0;
  a5=casadi_sq(a4);
  a5=(a1*a5);
  a3=(a3+a5);
  a5=1.;
  a3=(a3-a5);
  a3=(a0*a3);
  a6=arg[0] ? arg[0][8] : 0;
  a7=(a1*a2);
  a8=arg[0] ? arg[0][6] : 0;
  a7=(a7*a8);
  a9=(a1*a4);
  a10=arg[0] ? arg[0][5] : 0;
  a9=(a9*a10);
  a7=(a7-a9);
  a7=(a6*a7);
  a3=(a3-a7);
  a7=arg[0] ? arg[0][9] : 0;
  a9=(a1*a2);
  a9=(a9*a10);
  a11=(a1*a4);
  a11=(a11*a8);
  a9=(a9+a11);
  a9=(a7*a9);
  a3=(a3+a9);
  if (res[0]!=0) res[0][0]=a3;
  a3=casadi_sq(a2);
  a3=(a1*a3);
  a9=casadi_sq(a10);
  a9=(a1*a9);
  a3=(a3+a9);
  a3=(a3-a5);
  a3=(a6*a3);
  a9=(a1*a2);
  a9=(a9*a8);
  a11=(a1*a4);
  a11=(a11*a10);
  a9=(a9+a11);
  a9=(a0*a9);
  a3=(a3+a9);
  a9=(a1*a2);
  a9=(a9*a4);
  a11=(a1*a10);
  a11=(a11*a8);
  a9=(a9-a11);
  a9=(a7*a9);
  a3=(a3-a9);
  if (res[0]!=0) res[0][1]=a3;
  a3=casadi_sq(a2);
  a3=(a1*a3);
  a9=casadi_sq(a8);
  a9=(a1*a9);
  a3=(a3+a9);
  a3=(a3-a5);
  a3=(a7*a3);
  a9=(a1*a2);
  a9=(a9*a10);
  a11=(a1*a4);
  a11=(a11*a8);
  a9=(a9-a11);
  a9=(a0*a9);
  a3=(a3-a9);
  a9=(a1*a2);
  a9=(a9*a4);
  a11=(a1*a10);
  a11=(a11*a8);
  a9=(a9+a11);
  a9=(a6*a9);
  a3=(a3+a9);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0] ? arg[0][10] : 0;
  a9=(a4*a3);
  a9=(a9/a1);
  a11=arg[0] ? arg[0][11] : 0;
  a12=(a10*a11);
  a12=(a12/a1);
  a9=(a9+a12);
  a12=arg[0] ? arg[0][12] : 0;
  a13=(a8*a12);
  a13=(a13/a1);
  a9=(a9+a13);
  a9=(-a9);
  if (res[0]!=0) res[0][3]=a9;
  a9=(a2*a3);
  a9=(a9/a1);
  a13=(a8*a11);
  a13=(a13/a1);
  a9=(a9-a13);
  a13=(a10*a12);
  a13=(a13/a1);
  a9=(a9+a13);
  if (res[0]!=0) res[0][4]=a9;
  a9=(a8*a3);
  a9=(a9/a1);
  a13=(a2*a11);
  a13=(a13/a1);
  a9=(a9+a13);
  a13=(a4*a12);
  a13=(a13/a1);
  a9=(a9-a13);
  if (res[0]!=0) res[0][5]=a9;
  a9=(a4*a11);
  a9=(a9/a1);
  a13=(a10*a3);
  a13=(a13/a1);
  a9=(a9-a13);
  a13=(a2*a12);
  a13=(a13/a1);
  a9=(a9+a13);
  if (res[0]!=0) res[0][6]=a9;
  a9=(a6*a12);
  a13=(a7*a11);
  a9=(a9-a13);
  a13=9.8000000000000007e+00;
  a14=(a1*a2);
  a14=(a14*a10);
  a15=(a1*a4);
  a15=(a15*a8);
  a14=(a14-a15);
  a14=(a13*a14);
  a9=(a9-a14);
  if (res[0]!=0) res[0][7]=a9;
  a7=(a7*a3);
  a9=(a0*a12);
  a7=(a7-a9);
  a9=(a1*a2);
  a9=(a9*a4);
  a10=(a1*a10);
  a10=(a10*a8);
  a9=(a9+a10);
  a9=(a13*a9);
  a7=(a7+a9);
  if (res[0]!=0) res[0][8]=a7;
  a0=(a0*a11);
  a6=(a6*a3);
  a0=(a0-a6);
  a2=casadi_sq(a2);
  a2=(a1*a2);
  a8=casadi_sq(a8);
  a1=(a1*a8);
  a2=(a2+a1);
  a2=(a2-a5);
  a13=(a13*a2);
  a0=(a0+a13);
  a13=3.1582000000000002e-04;
  a2=arg[1] ? arg[1][0] : 0;
  a5=casadi_sq(a2);
  a1=arg[1] ? arg[1][1] : 0;
  a8=casadi_sq(a1);
  a5=(a5+a8);
  a8=arg[1] ? arg[1][2] : 0;
  a6=casadi_sq(a8);
  a5=(a5+a6);
  a6=arg[1] ? arg[1][3] : 0;
  a7=casadi_sq(a6);
  a5=(a5+a7);
  a13=(a13*a5);
  a5=3.3000000000000002e-02;
  a13=(a13/a5);
  a0=(a0-a13);
  if (res[0]!=0) res[0][9]=a0;
  a0=1.0264150000000001e-05;
  a13=casadi_sq(a2);
  a5=casadi_sq(a1);
  a13=(a13+a5);
  a5=casadi_sq(a8);
  a13=(a13-a5);
  a5=casadi_sq(a6);
  a13=(a13-a5);
  a13=(a0*a13);
  a5=1.3950000000000000e-05;
  a7=(a5*a11);
  a7=(a7*a12);
  a13=(a13-a7);
  a7=2.1730000000000000e-05;
  a9=(a7*a11);
  a9=(a9*a12);
  a13=(a13+a9);
  a13=(a13/a5);
  a13=(-a13);
  if (res[0]!=0) res[0][10]=a13;
  a13=casadi_sq(a2);
  a9=casadi_sq(a1);
  a13=(a13-a9);
  a9=casadi_sq(a8);
  a13=(a13-a9);
  a9=casadi_sq(a6);
  a13=(a13+a9);
  a0=(a0*a13);
  a13=(a5*a3);
  a13=(a13*a12);
  a0=(a0+a13);
  a13=(a7*a3);
  a13=(a13*a12);
  a0=(a0-a13);
  a0=(a0/a5);
  a0=(-a0);
  if (res[0]!=0) res[0][11]=a0;
  a0=7.9379000000000007e-06;
  a2=casadi_sq(a2);
  a1=casadi_sq(a1);
  a2=(a2-a1);
  a8=casadi_sq(a8);
  a2=(a2+a8);
  a6=casadi_sq(a6);
  a2=(a2-a6);
  a0=(a0*a2);
  a2=(a5*a3);
  a2=(a2*a11);
  a0=(a0-a2);
  a5=(a5*a3);
  a5=(a5*a11);
  a0=(a0+a5);
  a0=(a0/a7);
  a0=(-a0);
  if (res[0]!=0) res[0][12]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void crazyflie_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_expl_ode_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* crazyflie_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crazyflie_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
