<?xml version="1.0"?>
<package format="3">
  <name>crazyflie_nmpc</name>
  <version>2.0.0</version>
  <description>ROS2 integration for Crazyflie Nano Quadcopter from Bitcraze</description>

  <maintainer email="whoenig@usc.edu">Wolfgang Hoenig</maintainer>
  <maintainer email="barros@diag.uniroma1.it">Barbara Barros Carlos</maintainer>
  <maintainer email="tommaso.sartor@imtek.uni-freiburg.de">Tommaso Sartor</maintainer>

  <license>MIT</license>

  <author email="whoenig@usc.edu">Wolfgang Hoenig</author>
  <author email="barros@diag.uniroma1.it">Barbara Barros Carlos</author>
  <author email="tommaso.sartor@imtek.uni-freiburg.de">Tommaso Sartor</author>

  <!-- Build system dependency -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies needed to build or run -->
  <depend>crazyflie_controller</depend>

  <export>
    <!-- Mark as an ament package -->
    <build_type>ament_cmake</build_type>
  </export>
</package>
