SOURCES = [ 'acados_solver_sfunction_crazyflie_pos.c ', ...
            'acados_solver_crazyflie_pos.c ', ...
            'crazyflie_pos_model/crazyflie_pos_expl_ode_fun.c ', ...
            'crazyflie_pos_model/crazyflie_pos_expl_vde_forw.c ',...
            ];

INC_PATH = '/usr/local/include';

INCS = [ ' -I', INC_PATH, '/blasfeo/include/ ', ...
          '-I', INC_PATH, ' -I', INC_PATH, '/acados/ ', ...
          '-I', INC_PATH, '/qpOASES_e/' ];

CFLAGS  = ' -O';



LIB_PATH = '/usr/local/lib';

LIBS = '-lacados -lhpipm -lblasfeo -lqpOASES_e -lm'; 
    
eval( [ 'mex -v -output  acados_solver_sfunction_crazyflie_pos ', ...
    CFLAGS, INCS, ' ', SOURCES, ' -L', LIB_PATH, ' ', LIBS ]);

disp( [ 'acados_solver_sfunction_crazyflie_pos', '.', ...
    eval('mexext'), ' successfully created!'] );