/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crazyflie_pos_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[31] = {6, 4, 0, 6, 12, 18, 24, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s5[59] = {55, 1, 0, 55, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54};

/* crazyflie_pos_expl_ode_hess:(i0[6],i1[6x6],i2[6x4],i3[6],i4[4])->(o0[10],o1[55]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=arg[3] ? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[3] ? arg[3][1] : 0;
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[3] ? arg[3][2] : 0;
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[4] ? arg[4][2] : 0;
  a2=cos(a1);
  a3=arg[4] ? arg[4][1] : 0;
  a4=cos(a3);
  a5=2.7472527472527471e+01;
  a6=arg[3] ? arg[3][5] : 0;
  a6=(a5*a6);
  a4=(a4*a6);
  a7=(a2*a4);
  a8=arg[4] ? arg[4][3] : 0;
  a9=cos(a8);
  a10=sin(a3);
  a11=(a9*a10);
  a12=cos(a3);
  a13=sin(a1);
  a14=(a12*a13);
  a15=sin(a8);
  a16=(a14*a15);
  a11=(a11-a16);
  a16=arg[3] ? arg[3][4] : 0;
  a16=(a5*a16);
  a11=(a11*a16);
  a7=(a7-a11);
  a11=sin(a3);
  a17=sin(a8);
  a18=(a11*a17);
  a19=cos(a3);
  a20=cos(a8);
  a21=(a19*a20);
  a22=sin(a1);
  a23=(a21*a22);
  a18=(a18+a23);
  a23=arg[3] ? arg[3][3] : 0;
  a5=(a5*a23);
  a18=(a18*a5);
  a7=(a7+a18);
  if (res[0]!=0) res[0][6]=a7;
  a7=cos(a3);
  a18=arg[4] ? arg[4][0] : 0;
  a23=(a18*a5);
  a24=(a17*a23);
  a25=(a7*a24);
  a26=sin(a3);
  a27=(a18*a2);
  a27=(a27*a6);
  a28=(a26*a27);
  a29=sin(a3);
  a30=(a18*a16);
  a31=(a15*a30);
  a32=(a13*a31);
  a33=(a29*a32);
  a28=(a28+a33);
  a33=cos(a3);
  a34=(a9*a30);
  a35=(a33*a34);
  a28=(a28+a35);
  a35=sin(a3);
  a36=(a22*a23);
  a37=(a20*a36);
  a38=(a35*a37);
  a28=(a28+a38);
  a25=(a25-a28);
  if (res[0]!=0) res[0][7]=a25;
  a25=cos(a1);
  a28=(a12*a31);
  a38=(a25*a28);
  a39=sin(a1);
  a40=(a18*a4);
  a41=(a39*a40);
  a38=(a38-a41);
  a41=cos(a1);
  a42=(a21*a23);
  a43=(a41*a42);
  a38=(a38+a43);
  if (res[0]!=0) res[0][8]=a38;
  a38=cos(a8);
  a43=(a14*a30);
  a44=(a38*a43);
  a45=sin(a8);
  a46=(a10*a30);
  a47=(a45*a46);
  a44=(a44+a47);
  a47=sin(a8);
  a48=(a19*a36);
  a49=(a47*a48);
  a44=(a44-a49);
  a49=cos(a8);
  a50=(a11*a23);
  a51=(a49*a50);
  a44=(a44+a51);
  if (res[0]!=0) res[0][9]=a44;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[1]!=0) res[1][10]=a0;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a0;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a0;
  if (res[1]!=0) res[1][18]=a0;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a0;
  if (res[1]!=0) res[1][21]=a0;
  if (res[1]!=0) res[1][22]=a0;
  if (res[1]!=0) res[1][23]=a0;
  if (res[1]!=0) res[1][24]=a0;
  if (res[1]!=0) res[1][25]=a0;
  if (res[1]!=0) res[1][26]=a0;
  if (res[1]!=0) res[1][27]=a0;
  if (res[1]!=0) res[1][28]=a0;
  if (res[1]!=0) res[1][29]=a0;
  if (res[1]!=0) res[1][30]=a0;
  if (res[1]!=0) res[1][31]=a0;
  if (res[1]!=0) res[1][32]=a0;
  if (res[1]!=0) res[1][33]=a0;
  if (res[1]!=0) res[1][34]=a0;
  if (res[1]!=0) res[1][35]=a0;
  if (res[1]!=0) res[1][36]=a0;
  if (res[1]!=0) res[1][37]=a0;
  if (res[1]!=0) res[1][38]=a0;
  if (res[1]!=0) res[1][39]=a0;
  if (res[1]!=0) res[1][40]=a0;
  if (res[1]!=0) res[1][41]=a0;
  if (res[1]!=0) res[1][42]=a0;
  if (res[1]!=0) res[1][43]=a0;
  if (res[1]!=0) res[1][44]=a0;
  if (res[1]!=0) res[1][45]=a0;
  a17=(a17*a5);
  a7=(a7*a17);
  a2=(a6*a2);
  a26=(a26*a2);
  a15=(a15*a16);
  a2=(a13*a15);
  a29=(a29*a2);
  a26=(a26+a29);
  a9=(a9*a16);
  a33=(a33*a9);
  a26=(a26+a33);
  a22=(a22*a5);
  a33=(a20*a22);
  a35=(a35*a33);
  a26=(a26+a35);
  a7=(a7-a26);
  if (res[1]!=0) res[1][46]=a7;
  a15=(a12*a15);
  a15=(a25*a15);
  a4=(a39*a4);
  a15=(a15-a4);
  a21=(a21*a5);
  a21=(a41*a21);
  a15=(a15+a21);
  if (res[1]!=0) res[1][47]=a15;
  a14=(a14*a16);
  a14=(a38*a14);
  a10=(a10*a16);
  a10=(a45*a10);
  a14=(a14+a10);
  a22=(a19*a22);
  a22=(a47*a22);
  a14=(a14-a22);
  a11=(a11*a5);
  a11=(a49*a11);
  a14=(a14+a11);
  if (res[1]!=0) res[1][48]=a14;
  a14=sin(a3);
  a24=(a24*a14);
  a14=cos(a3);
  a27=(a27*a14);
  a14=cos(a3);
  a32=(a32*a14);
  a27=(a27+a32);
  a32=sin(a3);
  a34=(a34*a32);
  a27=(a27-a34);
  a34=cos(a3);
  a37=(a37*a34);
  a27=(a27+a37);
  a24=(a24+a27);
  a24=(-a24);
  if (res[1]!=0) res[1][49]=a24;
  a24=sin(a3);
  a6=(a6*a24);
  a18=(a18*a6);
  a39=(a39*a18);
  a18=sin(a3);
  a31=(a31*a18);
  a25=(a25*a31);
  a39=(a39-a25);
  a25=sin(a3);
  a20=(a20*a25);
  a20=(a23*a20);
  a41=(a41*a20);
  a39=(a39-a41);
  if (res[1]!=0) res[1][50]=a39;
  a39=cos(a3);
  a39=(a30*a39);
  a45=(a45*a39);
  a13=(a13*a18);
  a13=(a30*a13);
  a13=(a38*a13);
  a45=(a45-a13);
  a36=(a36*a25);
  a36=(a47*a36);
  a45=(a45+a36);
  a3=cos(a3);
  a3=(a23*a3);
  a49=(a49*a3);
  a45=(a45+a49);
  if (res[1]!=0) res[1][51]=a45;
  a45=sin(a1);
  a28=(a28*a45);
  a45=cos(a1);
  a40=(a40*a45);
  a28=(a28+a40);
  a40=sin(a1);
  a42=(a42*a40);
  a28=(a28+a42);
  a28=(-a28);
  if (res[1]!=0) res[1][52]=a28;
  a28=cos(a1);
  a12=(a12*a28);
  a30=(a30*a12);
  a38=(a38*a30);
  a1=cos(a1);
  a23=(a23*a1);
  a19=(a19*a23);
  a47=(a47*a19);
  a38=(a38-a47);
  if (res[1]!=0) res[1][53]=a38;
  a38=cos(a8);
  a46=(a46*a38);
  a38=sin(a8);
  a43=(a43*a38);
  a46=(a46-a43);
  a43=cos(a8);
  a48=(a48*a43);
  a46=(a46-a48);
  a8=sin(a8);
  a50=(a50*a8);
  a46=(a46-a50);
  if (res[1]!=0) res[1][54]=a46;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_ode_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_ode_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_ode_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
