/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crazyflie_pos_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[31] = {6, 4, 0, 6, 12, 18, 24, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* crazyflie_pos_expl_vde_forw:(i0[6],i1[6x6],i2[6x4],i3[4])->(o0[6],o1[6x6],o2[6x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][0] : 0;
  a1=arg[3] ? arg[3][1] : 0;
  a2=sin(a1);
  a3=arg[3] ? arg[3][3] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a6=cos(a1);
  a7=cos(a3);
  a8=(a6*a7);
  a9=arg[3] ? arg[3][2] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a5=(a5+a11);
  a11=(a0*a5);
  a12=3.6400000000000002e-02;
  a11=(a11/a12);
  if (res[0]!=0) res[0][3]=a11;
  a11=cos(a3);
  a13=sin(a1);
  a14=(a11*a13);
  a15=cos(a1);
  a16=sin(a9);
  a17=(a15*a16);
  a18=sin(a3);
  a19=(a17*a18);
  a14=(a14-a19);
  a19=(a0*a14);
  a19=(a19/a12);
  a19=(-a19);
  if (res[0]!=0) res[0][4]=a19;
  a19=3.5696205999999997e-01;
  a20=cos(a9);
  a21=(a0*a20);
  a22=cos(a1);
  a23=(a21*a22);
  a19=(a19-a23);
  a19=(a19/a12);
  a19=(-a19);
  if (res[0]!=0) res[0][5]=a19;
  a19=arg[1] ? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a19;
  a19=arg[1] ? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a19;
  a19=arg[1] ? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a19;
  a19=0.;
  if (res[1]!=0) res[1][3]=a19;
  if (res[1]!=0) res[1][4]=a19;
  if (res[1]!=0) res[1][5]=a19;
  a12=arg[1] ? arg[1][9] : 0;
  if (res[1]!=0) res[1][6]=a12;
  a12=arg[1] ? arg[1][10] : 0;
  if (res[1]!=0) res[1][7]=a12;
  a12=arg[1] ? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a12;
  if (res[1]!=0) res[1][9]=a19;
  if (res[1]!=0) res[1][10]=a19;
  if (res[1]!=0) res[1][11]=a19;
  a12=arg[1] ? arg[1][15] : 0;
  if (res[1]!=0) res[1][12]=a12;
  a12=arg[1] ? arg[1][16] : 0;
  if (res[1]!=0) res[1][13]=a12;
  a12=arg[1] ? arg[1][17] : 0;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a19;
  if (res[1]!=0) res[1][16]=a19;
  if (res[1]!=0) res[1][17]=a19;
  a12=arg[1] ? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a12;
  a12=arg[1] ? arg[1][22] : 0;
  if (res[1]!=0) res[1][19]=a12;
  a12=arg[1] ? arg[1][23] : 0;
  if (res[1]!=0) res[1][20]=a12;
  if (res[1]!=0) res[1][21]=a19;
  if (res[1]!=0) res[1][22]=a19;
  if (res[1]!=0) res[1][23]=a19;
  a12=arg[1] ? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a12;
  a12=arg[1] ? arg[1][28] : 0;
  if (res[1]!=0) res[1][25]=a12;
  a12=arg[1] ? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a12;
  if (res[1]!=0) res[1][27]=a19;
  if (res[1]!=0) res[1][28]=a19;
  if (res[1]!=0) res[1][29]=a19;
  a12=arg[1] ? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a12;
  a12=arg[1] ? arg[1][34] : 0;
  if (res[1]!=0) res[1][31]=a12;
  a12=arg[1] ? arg[1][35] : 0;
  if (res[1]!=0) res[1][32]=a12;
  if (res[1]!=0) res[1][33]=a19;
  if (res[1]!=0) res[1][34]=a19;
  if (res[1]!=0) res[1][35]=a19;
  a12=arg[2] ? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a12;
  a12=arg[2] ? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a12;
  a12=arg[2] ? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a12;
  a12=2.7472527472527471e+01;
  a5=(a12*a5);
  if (res[2]!=0) res[2][3]=a5;
  a14=(a12*a14);
  a14=(-a14);
  if (res[2]!=0) res[2][4]=a14;
  a20=(a22*a20);
  a20=(a12*a20);
  if (res[2]!=0) res[2][5]=a20;
  a20=arg[2] ? arg[2][9] : 0;
  if (res[2]!=0) res[2][6]=a20;
  a20=arg[2] ? arg[2][10] : 0;
  if (res[2]!=0) res[2][7]=a20;
  a20=arg[2] ? arg[2][11] : 0;
  if (res[2]!=0) res[2][8]=a20;
  a20=cos(a1);
  a4=(a4*a20);
  a20=sin(a1);
  a7=(a7*a20);
  a7=(a10*a7);
  a4=(a4-a7);
  a4=(a0*a4);
  a4=(a12*a4);
  if (res[2]!=0) res[2][9]=a4;
  a4=cos(a1);
  a11=(a11*a4);
  a4=sin(a1);
  a16=(a16*a4);
  a16=(a18*a16);
  a11=(a11+a16);
  a11=(a0*a11);
  a11=(a12*a11);
  a11=(-a11);
  if (res[2]!=0) res[2][10]=a11;
  a1=sin(a1);
  a21=(a21*a1);
  a21=(a12*a21);
  a21=(-a21);
  if (res[2]!=0) res[2][11]=a21;
  a21=arg[2] ? arg[2][15] : 0;
  if (res[2]!=0) res[2][12]=a21;
  a21=arg[2] ? arg[2][16] : 0;
  if (res[2]!=0) res[2][13]=a21;
  a21=arg[2] ? arg[2][17] : 0;
  if (res[2]!=0) res[2][14]=a21;
  a21=cos(a9);
  a8=(a8*a21);
  a8=(a0*a8);
  a8=(a12*a8);
  if (res[2]!=0) res[2][15]=a8;
  a8=cos(a9);
  a15=(a15*a8);
  a18=(a18*a15);
  a18=(a0*a18);
  a18=(a12*a18);
  if (res[2]!=0) res[2][16]=a18;
  a9=sin(a9);
  a9=(a0*a9);
  a22=(a22*a9);
  a22=(a12*a22);
  a22=(-a22);
  if (res[2]!=0) res[2][17]=a22;
  a22=arg[2] ? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a22;
  a22=arg[2] ? arg[2][22] : 0;
  if (res[2]!=0) res[2][19]=a22;
  a22=arg[2] ? arg[2][23] : 0;
  if (res[2]!=0) res[2][20]=a22;
  a22=cos(a3);
  a2=(a2*a22);
  a22=sin(a3);
  a6=(a6*a22);
  a10=(a10*a6);
  a2=(a2-a10);
  a2=(a0*a2);
  a2=(a12*a2);
  if (res[2]!=0) res[2][21]=a2;
  a2=sin(a3);
  a13=(a13*a2);
  a3=cos(a3);
  a17=(a17*a3);
  a13=(a13+a17);
  a0=(a0*a13);
  a12=(a12*a0);
  if (res[2]!=0) res[2][22]=a12;
  if (res[2]!=0) res[2][23]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_vde_forw_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
