/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) crazyflie_pos_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

/* crazyflie_pos_expl_vde_adj:(i0[6],i1[6],i2[4])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1] ? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2] ? arg[2][2] : 0;
  a1=cos(a0);
  a2=arg[2] ? arg[2][1] : 0;
  a3=cos(a2);
  a4=2.7472527472527471e+01;
  a5=arg[1] ? arg[1][5] : 0;
  a5=(a4*a5);
  a3=(a3*a5);
  a6=(a1*a3);
  a7=arg[2] ? arg[2][3] : 0;
  a8=cos(a7);
  a9=sin(a2);
  a10=(a8*a9);
  a11=cos(a2);
  a12=sin(a0);
  a13=(a11*a12);
  a14=sin(a7);
  a15=(a13*a14);
  a10=(a10-a15);
  a15=arg[1] ? arg[1][4] : 0;
  a15=(a4*a15);
  a10=(a10*a15);
  a6=(a6-a10);
  a10=sin(a2);
  a16=sin(a7);
  a17=(a10*a16);
  a18=cos(a2);
  a19=cos(a7);
  a20=(a18*a19);
  a21=sin(a0);
  a22=(a20*a21);
  a17=(a17+a22);
  a22=arg[1] ? arg[1][3] : 0;
  a4=(a4*a22);
  a17=(a17*a4);
  a6=(a6+a17);
  if (res[0]!=0) res[0][6]=a6;
  a6=cos(a2);
  a17=arg[2] ? arg[2][0] : 0;
  a4=(a17*a4);
  a16=(a16*a4);
  a6=(a6*a16);
  a16=sin(a2);
  a1=(a17*a1);
  a1=(a1*a5);
  a16=(a16*a1);
  a1=sin(a2);
  a15=(a17*a15);
  a14=(a14*a15);
  a12=(a12*a14);
  a1=(a1*a12);
  a16=(a16+a1);
  a1=cos(a2);
  a8=(a8*a15);
  a1=(a1*a8);
  a16=(a16+a1);
  a2=sin(a2);
  a21=(a21*a4);
  a19=(a19*a21);
  a2=(a2*a19);
  a16=(a16+a2);
  a6=(a6-a16);
  if (res[0]!=0) res[0][7]=a6;
  a6=cos(a0);
  a11=(a11*a14);
  a6=(a6*a11);
  a11=sin(a0);
  a17=(a17*a3);
  a11=(a11*a17);
  a6=(a6-a11);
  a0=cos(a0);
  a20=(a20*a4);
  a0=(a0*a20);
  a6=(a6+a0);
  if (res[0]!=0) res[0][8]=a6;
  a6=cos(a7);
  a13=(a13*a15);
  a6=(a6*a13);
  a13=sin(a7);
  a9=(a9*a15);
  a13=(a13*a9);
  a6=(a6+a13);
  a13=sin(a7);
  a18=(a18*a21);
  a13=(a13*a18);
  a6=(a6-a13);
  a7=cos(a7);
  a10=(a10*a4);
  a7=(a7*a10);
  a6=(a6+a7);
  if (res[0]!=0) res[0][9]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void crazyflie_pos_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_vde_adj_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int crazyflie_pos_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* crazyflie_pos_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* crazyflie_pos_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int crazyflie_pos_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
